# https://travis-ci.org/ishikota/pymcts
language: python
python:
    - 2.7
install:
    - pip install coverage
    - pip install coveralls
script: nosetests --with-coverage pypoker/
after_success:
    - coveralls
notifications:
    email: false
    slack: kotaishimoto:mnkx14uWrYj3KKKXPOJT40dy
